### ISSUE TITLE
Airtable Create Row

### ISSUE THREAD

**Issue by btmoore4** [MutualAidNYC/airtable_gateway#10]
- Use the airtable API to create a "CreateRow Function" using "MANYC Sends to Group" object
- Eventually will need to play nice with custom mapping

**Comment by brainomite** [comment]
From what I understand based on the "Standards to Communicate between MANYC & Airtable Gateway" this is our OUTBOUND standard.

I believe you do mean "Group Sends New Needs Request to MANYC" object. Please confirm.

**Comment by brainomite** [comment]
2 more questions:

1. What base are we writing to?
2. Any idea of what the function signature should be

**Comment by btmoore4** [comment]
The base will be the same BASE_ID that is being polled. 
I am thinking something like 
`def addRow(API_KEY, BASE_ID, columnValueMap)`
