### ISSUE TITLE
Write UPDATE for Client Group Airtable

### ISSUE THREAD

**Issue by btmoore4** [MutualAidNYC/airtable_gateway#24]
We need to be able to 'update' a needs request from the client group airtable given a request ID. We will need to search the request IDs of the table, and then update the row if it exists, else create a new row.

**Comment by brainomite** [comment]
This request (at this time) doesn't make sense. In the specs, there is no agreed-upon format for MANYC to send anything but a delete request once the record has been created.

**Comment by btmoore4** [comment]
Gotcha yes there is only Add / Delete for format coming from MANYC. I think to start this should not be thought of a REST UPDATE task, but creating a function that using the Airtable API can update a row. 

For example, the function signature would look something like this: 
`const updateAirtableRows = (
    apiKey,
    baseId,
    tableName,
    updateRecord,
    uniqueId, 
    fieldValueMap = defaultMap,
) => {`

**Comment by brainomite** [comment]
heh already wrote all of this when I did issue #23, just need to factor out a generic update function
