### ISSUE TITLE
Debug Client Airtable Polling

### ISSUE THREAD

**Issue by btmoore4** [MutualAidNYC/airtable_gateway#9]
- Poll client airtable using https://github.com/crownheightsaid/airtable-change-detector or any other polling library
- Make sure its only picking up changed records to minimize calls.

**Comment by brainomite** [comment]
I took a look at the Airtable Base you were working with. I copied it to my own workspace.
The error is that the `last processed` field wasn't configured correctly. Take a look at the below settings and ensure that ALL the settings for the field match. 


![image](https://user-images.githubusercontent.com/11599888/80931906-d5314280-8d8a-11ea-916c-39f65d1f987c.png)

**Comment by btmoore4** [comment]
👍 
Tested it with my Test Airtable and looks good. 
Definitely working well enough for first attempt at spinning up, and we can customize later
